
#' @title AUC for BART object
#'
#' @description
#' An all-purpose model diagnostic, that mostly generates an AUC value and receiver operator curve. It also prints the optimal threshold based on the true skill statistic (and return the associated Type I and II error rates).
#'
#' @param model A BART model object generated by the dbarts package 
#'
#' @export
#'

bart.auc <- function(model) {
 
  true.vector <- model$fit$data@y
  
  pred <- prediction(colMeans(pnorm(model$yhat.train)), true.vector)
  
  perf.tss <- performance(pred,"sens","spec")
  tss.list <- (perf.tss@x.values[[1]] + perf.tss@y.values[[1]] - 1)
  tss.df <- data.frame(alpha=perf.tss@alpha.values[[1]],tss=tss.list)
  plot(tss.df,type='l')
  
  print('AUC = ')
  print(performance(pred,"auc")@y.values[[1]])
  plot(performance(pred, "tpr", "fpr"),main='Receiver operator curve')
  abline(0,1,col='red')
  
  thresh <- tss.df$alpha[which(tss.df$tss==max(tss.df$tss))]
  print('TSS threshold')
  print(thresh)

  print('Type I error rate')
  print(1-perf.tss@y.values[[1]][which(perf.tss@alpha.values[[1]]==thresh)]) # Type I error rate
  print('Type II error rate')
  print(1-perf.tss@x.values[[1]][which(perf.tss@alpha.values[[1]]==thresh)]) # Type II error rate

}
