#' @title Full-service variable selection
#'
#' @description
#'
#' A wrapper for a few core functions, including a few diagnostic plots of variable importance, and the automated stepwise variable set reduction algorithm. 
#'
#' @param xdata A data frame of covariates
#' @param ydata A vector of outcomes (1/0)
#' @param iter.step How many BART models to run for each iteration of the stepwise reduction
#' @param tree.step How many trees to use in the variable set reduction.Should be a SMALL number (10 or 20 trees) in order to create the maximum disparity in variable importance between informative and uninformative predictors (recommendations taken from Chipman et al. 2010).
#' @param iter.plot How many iterations to use in the first diagnostic plot 
#' @param full If this is set to FALSE (by default), this runs a stepwise variable set reduction and returns a model with the optimal variable step - much like gbm::gbm.step() or similar functions. In running varimp.step() it generates a single plot of RMSE against variables dropped. If this is set to TRUE, it also runs summary() on the model, and two additional plots are generated: the initial variable importance diagnostic generated by varimp.diag() (this is SLOW), and a final variable importance bar chart for the final model.  
#' 
#' @return Returns a model object run with the optimal, reduced variable set.
#' 
#' @export
#'
#'
#'

bart.step <- function(xdata, ydata,
                      iter.step=100, tree.step=10,
                      iter.plot=100,
                      full=FALSE,
                      quiet=FALSE) {

  quiet2 <- quiet
  if(full==TRUE){varimp.diag(xdata, ydata, iter=iter.plot, quiet=quiet2)}
  vs <- variable.step(xdata, ydata, n.trees=tree.step, iter=iter.step, quiet=quiet2)
  invisible(best.model <- bart(xdata[,vs], ydata, keeptrees=TRUE))
  if(full==TRUE){varimp(best.model, plots=TRUE)}
  if(full==TRUE) {summary(best.model, plots=TRUE)} else 
                 {summary(best.model, plots=FALSE)}
  invisible(best.model)
}
